name: my_flutter_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_svg: ^2.0.13
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  tflite_flutter: ^0.10.4
  image: ^4.3.0
  ffi: ^2.1.3
  url_launcher: ^6.3.1
  firebase_storage: ^12.3.7
  intl: ^0.19.0
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  
  assets:
    - assets/sign.png
    - assets/login.png
    - assets/dentai.png
    - assets/background.png
    - assets/modelimm.tflite



  